### ISSUE TITLE
How to change label value programmatically?

### ISSUE THREAD

**Issue by myinnos** [yuebinyun/debug-badge#1]

**Comment by yuebinyun** [comment]
The icon can not be changed via programmatically while the app is running.
The icon with label is generated when the APK (debug version) is generated
Sorry for my poor English.

**Comment by myinnos** [comment]
So `programmatically ` we cannot change `label `?

**Comment by yuebinyun** [comment]
Sorry，we can't change label via `programmatically`.
We can set label info in `build.gradle` (app module)
```gradle
badge {
  /* The label you want to show*/
  // label = "${project.android.defaultConfig.versionCode}"   // version code
  // label = "${project.android.defaultConfig.versionName}" // version name
  // label = "Debug" 
  label = "Dev"
}
```

**Comment by myinnos** [comment]
`OK! ` **Thank you!**
